name: Tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - login_page
          - product_page

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Allure and Chromium dependencies
      run: |
        sudo apt update
        # Устанавливаем зависимости для Chromium с актуальными именами пакетов
        sudo apt install -y openjdk-11-jdk libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 \
          libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 \
          libxrandr2 libgbm1 libasound2t64  # Изменено здесь
        
        # Установка Allure
        wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
        tar -xzf allure-2.24.0.tgz
        sudo mv allure-2.24.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install playwright pytest-playwright

    - name: Cache Playwright browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json', '**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install Playwright (только Chromium)
      run: npx playwright install chromium

    - name: Tests for Login page
      if: "github.event.inputs.deployment_target == 'login_page'"
      run: python -m pytest tests/test_login_page.py --alluredir=allure-results
    - name: Tests for Product page
      if: "github.event.inputs.deployment_target == 'product_page'"
      run: python -m pytest tests/test_product_page.py --alluredir=allure-results

    - name: Generate Allure report
      run: allure generate allure-results --clean -o allure-report

    - name: Upload Allure report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report