name: Tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - login_page
          - product_page


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install playwright pytest-playwright

    - name: Install Playwright system dependencies and browsers
      run: |
        npx playwright install --with-deps

    - name: Tests for Login page
      if: "github.event.inputs.deployment_target == 'login_page'"
      run: python -m pytest tests/test_login_page.py
    - name: Tests for Product page
      if: "github.event.inputs.deployment_target == 'product_page'"
      run: python -m pytest tests/test_product_page.py